[package]
name = "vamboo"
version = "0.1.0"
authors = ["tock203 <tick@tock.tech>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
pseudo = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
failure = "0.1"
bincode = "1.0"
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.2"
