[package]
name = "vamboo"
version = "0.1.0"
authors = ["tock203 <tick@tock.tech>"]
edition = "2018"

[dependencies]
stdweb = "0.4"
pseudo = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
failure = "0.1"
bincode = "1.0"
