[package]
name = "runtime"
version = "0.1.0"
authors = ["tock203 <tick@tock.tech>"]
license = "MPL-2.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
compiler = { path = "../compiler" }
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.2"
pseudo = "0.2"
