[package]
name = "editor"
version = "0.1.0"
description = "A visual programming language for web frontend."
authors = ["tock203 <tick@tock.tech>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
wasm-pack = "0.6"

[dependencies]
wasm-bindgen = "0.2"
# frappe = { git = "https://github.com/darkstalker/frappe", rev = "2c3e8cb386fa3b0a170b90ab097e2e3290543ed0" }
# frappe-dom = { git = "https://github.com/tock203/frappe-dom", rev = "3f4d6c9cdcbc43e01b6881e11600af3940d353f0" }
maplit = "1.0"
maybe-owned = "0.3"

[dependencies.web-sys]
version = "0.3"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
  'Event',
  'EventTarget',
  'MouseEvent'
]

